### ISSUE TITLE
Make Results and UnionCase Classes more Unit-Testable

### ISSUE THREAD

**Issue by JMarianczuk** [bluehands/Funicular-Switch#22]
This is less of an Issue and more a Feature request, but this seemed to be the right place to start a discussion.

When in a Unit Test a Result<> is returned, i would like to (easily) check, if it was successful, or e.g. with a custom result, which error type was returned.
And then assert further on the ok or error.
With FluentAssertions this can be done nicely, but required additional helper-methods, which can be generated.
This may look something like this (for a custom Result OperationResult with error type Failure and one example Failure "Forbidden":

Usage would look like this
```csharp
var operationResult = ...
operationResult.Should().BeOk();
operationResult
    .Should().BeForbiddenResult()
    .Which.Message.Should().NotBeEmpty();
```

With this being the code that enables the example above:
```csharp
public static class ResultFluentAssertionsExtensions
{
    public static OperationResultAssertions<T> Should<T>(this OperationResult<T> result) => new(result);
}

public class OperationResultAssertions<T> : ObjectAssertions<OperationResult<T>, OperationResultAssertions<T>>
{

    public OperationResultAssertions(OperationResult<T> actualValue) : base(actualValue)
    {
    }

    ppublic AndWhichConstraint<OperationResultAssertions<T>, T> BeOk(string because = "", params object[] becauseArgs)
    {
        Execute.Assertion
            .ForCondition(this.Subject.IsOk)
            .BecauseOf(because, becauseArgs)
            .FailWith("Expected {context} to be Ok{reason}, but found {0}", this.Subject);

        return new(this, this.Subject.GetValueOrDefault()!);
    }

    public AndWhichConstraint<OperationResultAssertions<T>, Failure> BeError(string because = "", params object[] becauseArgs)
    {
        Execute.Assertion
            .ForCondition(this.Subject.IsError)
            .BecauseOf(because, becauseArgs)
            .FailWith("Expected {context} to be Error{reason}, but found {0}", this.Subject);

        return new(this, this.Subject.GetErrorOrDefault()!);
    }

    public AndWhichConstraint<OperationResultAssertions<T>, Failure.Forbidden_> BeForbiddenResult(string because = "", params object[] becauseArgs)
    {
        Execute.Assertion
            .ForCondition(this.Subject.GetErrorOrDefault()! is Failure.Forbidden_)
            .BecauseOf(because, becauseArgs)
            .FailWith("Expected {context} to be Error with Forbidden Failure{reason}, but found {0}", this.Subject);

        return new(this, (this.Subject.GetErrorOrDefault() as Failure.Forbidden_)!);
    }
}
```
The generic IsError assertion would be for a case, where checking that the result is not okay is sufficient. This would be equivalent to an IsNotOk method that may be generated as well for further expressivity.

The generator would then generate for all Sub-Classes of the error type corresponding methods.
This may also be applicable for types that have the UnionCase Attribute, such that we can Assert that they are a certain subtype, similar to the match method.
To not clutter the production code, this should be generated only in the test project. Maybe a assembly level attribute with the type of the result(s) to generate the methods for?

**Comment by ax0l0tl** [comment]
Hi, generic IsOk and IsError assertion can already be formulated as 
`
calc.IsOk.Should().BeTrue();
calc.IsError.Should().BeTrue();
`
Nevertheless I like the idea to have nice fluent assertions support for generated result types. It could be achieved with a generator package that is referenced in unit test projects only, which would add the code proposed in the issue.

**Comment by ax0l0tl** [comment]
Test support for Union and Result types now comes with the FunicularSwitch.Generators.FluentAssertions package.
