### ISSUE TITLE
Add support for query-expression pattern in Option and Result

### ISSUE THREAD

**Issue by Tyrrx** [bluehands/Funicular-Switch#32]
It would be great if the query-expression pattern is usable with the Result and Option because sometimes, especially when gluing together application logic, it is required that values need to be passed through the whole execution path. This can e.g. be done by creating new tuples that carry the required values through the execution path but this becomes unreadable and annoying very fast. 
Additionally, when adding new values that need to be carried through, a lot of unnecessary changes are required that can be avoided using the query-expression pattern.

The query expression pattern is defined in [12.20.4 The query-expression pattern](https://github.com/dotnet/csharpstandard/blob/draft-v8/standard/expressions.md#12204-the-query-expression-pattern).

I would suggest adding support for the monadic `Map` and `Bind` by implementing `Select` and `SelectMany` as extensions for Option and Result.

**Comment by Tyrrx** [comment]
@ax0l0tl Can you please take a look at this. There might be some missing permutations.

**Comment by ax0l0tl** [comment]
Implemented in FuniuclarSwitch and FuniuclarSwitch.Generators.
